# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: ros:iron

pipelines:
  default:
    - parallel:
      - step:
          name: '1 step build'
          script:
            - apt-get update
            - apt-get install -y openssh-client
            - ./setup_devenv.sh
            - ls
            - ls src/
            - ls /opt/ros/iron/
            - source /opt/ros/iron/setup.bash
            - ./build.sh
            - ls
            - ls install/
      # - step:
      #     name: 'Install dependancies and build'
      #     script:
      #       - echo "Install and build"
      #       - ./build.sh
      # - step:
      #     name: 'Test'
      #     script:
      #       - echo "Testing"
      #       - ./run_explorer.sh
